# Generated by Django 5.1.6 on 2025-03-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobmatchanalysis',
            table='job_matching_jobmatchanalysis',
        ),
    ]
