# Generated by Django 5.1.6 on 2025-03-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_matching', '0003_alter_jobmatchanalysis_keyword_matches_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('job_description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='JobMatchAnalysis',
        ),
    ]
